### ISSUE TITLE
[3.0] Move AppBundle/* into app/

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-standard#803]
Hi guys!

This is a proposal to move everything inside `src/AppBundle` into the `app/` directory and then remove the `AppBundle` entirely. This was too big of a change to make before 3.0, but now I think it's time :).

ALSO, the `src/` directory would remain, and it would be recommended as a best practice to put code here that you want to have decoupled from your framework. These could be re-usable bundles, or just libraries.

## Example

In symfony/symfony-standard#584, a lot of thought and work resulted in the 3.0 directory structure. I have an example that builds off of that:

* [Current 3.0 structure](https://github.com/weaverryan/symfony3-dir-structure)
* [Proposed structure](https://github.com/weaverryan/symfony-demo/tree/move_app_bundle)

Try out the new structure - it's a functional project (with more details below).

## The Problem

**The code you touch to build an application is spread out between the `app/`
directory and the `src/AppBundle` directory.**

This causes common workflows (e.g. building a Controller with a template) to necessitate moving around through a lot of directories. There is also confusion between `app/` and `AppBundle`.

## Proposed Solution

A) `cp src/AppBundle/* app/`
B) Add a PSR-4 autoload for the `app/` directory in [composer.json](https://github.com/weaverryan/symfony-demo/blob/move_app_bundle/composer.json#L8) (and update namespaces to `App/`)
C) Delete `AppBundle.php`
D) Remove places where we use the bundle. This last point included:

1) Not using `_controller` - just using the full class name: https://github.com/weaverryan/symfony-demo/blob/move_app_bundle/app/Resources/views/blog/post_show.html.twig#L18
2) Registering a new `App:Post`-styled Doctrine alias: https://github.com/weaverryan/symfony-demo/blob/move_app_bundle/app/config/config.yml#L74-L80
3) Change routing import to not use `@AppBundle`

## BC Breaks

This change can be done today without any core changes and without breaking anything that uses the "old" structure. Bundles still work *exactly* like before.

So, this has no BC breaks, other than breaking from existing documentation, blog posts, etc. That's not to be taken lightly.

## TODOS

Practically speaking, a number of changes would need to be made to core:

**NEEDS**

* [ ] `Kernel::locateResource` has no way to load things from the kernel root directory, and this would need to change. I'm hacking around this to load the Controller annotations [here](https://github.com/weaverryan/symfony-demo/blob/move_app_bundle/app/config/routing.yml#L7-L10) and [here](https://github.com/weaverryan/symfony-demo/blob/move_app_bundle/app/AppKernel.php#L43-L50)

* [ ] Need to load commands automatically from `%kernel.root_dir%/Command` (easy, see `Application::registerCommands`)

* [ ] The SensioDistributionBundle currently has some crazy hackage to change the StandardEdition into the 3.0 structure (https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Composer/ScriptHandler.php#L398). We should now actually update the master branch of the SE to the correct structure.

* [ ] Get 3rd-party bundles to look in `%kernel.root_dir` for things. For example, DoctrineFixturesBundle should look in `app/DataFixtures` in addition to the bundles.

**WANTS**

* [ ] Need a way to load YML/XML mapping from the `app/` directory. I've  manually added a new mapping to `config.yml`, but it only loads annotations (but this could be easily changed by the user).

* [ ] Ability to register compiler passes from `AppKernel`

* [ ] Ability to add classes to the "class cache" from `AppKernel`

Thanks!

**Comment by Pierstoval** [comment]
Wow, this is awesome, I can't wait to see these features released in 3.0 ! :+1: 
 
I'm gonna share this in some networks to make other developers come and help :)

**Comment by Tobion** [comment]
With these changes one more inconsistency becomes obvious: Capitalization of `config` vs `Resources`. config is now the only lowercase folder inside `app`. IMO either we also lowercase `resources`, i.e. folders that do not contain PHP classes are lowercased. Or config should be uppercased as well.

**Comment by jvasseur** [comment]
Having the AppKernel in the global namespace is confusing considering the app directory is mapped to the App namespace.

It could be moved to the App namespace but this would need prefixing all bundle names with \

**Comment by aitboudad** [comment]
:+1: 

@Tobion or moving `config` folder inside `Resources` ?

**Comment by Pierstoval** [comment]
I also think that the `config` dir should be accessible at the root directory, and `resources` in the `app` dir

**Comment by Tobion** [comment]
If the premise is that `app` contains framework-specific stuff, then `config` should stay in there as it is also framework-specific.

**Comment by stof** [comment]
And if you have multiple kernels, the config is only for a single kernel. So it makes sense to keep it inside ``app``, alongside the ``AppKernel`` instead of moving it at the root (which would then require finding a different project structure for multi-kernel apps, while the current one works fine)

**Comment by weaverryan** [comment]
@jvasseur You're right - I put AppKernel and AppCache in the `App/` namespace - I had meant to do this (https://github.com/weaverryan/symfony-demo/commit/1abbee59f6e62071563eaca48dede43e76c82299). It now means these classes are autoloaded like normal.

@Tobion That inconsistency also stuck out to me. I think changing `Resources` to `resources` is too big a BC break. Changing `config` => `Config` would be inconsistent with bundles. Moving `config` into `app/Resources` makes this important directly too deep.

In #584, moving `config` to root was talked about (see Configuration header: https://github.com/symfony/symfony-standard/issues/584#issuecomment-23148928) and had some support. Moving it out of `app/` breaks the "app" contract (that all app code lives there), but the `config/` directory is already special in `app/`, because it's the one spot where things don't look like a bundle. Moving it to the root would solve the capitalization inconsistency (which devs will certainly notice) and move this important directory one level further up. We can easily document how you'd evolve from this structure for multiple kernels.

**Comment by cordoval** [comment]
:-1:


because it seems the confusion will be greater when we open app folder and we see all those classes and then we will be jumping now into full directory structures src and app to develop php code.

I think is best to move app into src and not the other way around. Under src you should have App or whatever folder you want to call it and you can use freely the namespaces. You would then not have to hack anything at all. No need to break documentation either. The only things would be to just point or configure what is the overriding folder for templates and well configuration you wouldn't need to do much just some imports.

**Comment by Pierstoval** [comment]
What about `app/.config` and `app/.resources` ?

**Comment by stof** [comment]
@Pierstoval Please no. Important files should not be placed in hidden folders

**Comment by Pierstoval** [comment]
Even with an underscore `_` instead of the dot ?

**Comment by stof** [comment]
The dot is what makes the folder hidden.

But I don't like the underscore either

**Comment by Pierstoval** [comment]
I knew about the dot, and I totally understand that you're against this idea (I am too), it's just that the situation about these two directories under the `app` dir is kinda tricky, so, you see, let's propose anything :yum:

**Comment by WouterJ** [comment]
Some thoughts:

* Globally speaken, I like this idea
* Instead of not making it a bundle and having inconsistent behaviour, what about automatically registering an AppBundle, just like I did in https://github.com/WouterJ/Bundleless ?
* For compiler passes, this PR should solve it: https://github.com/symfony/symfony/pull/13761
* I don't like having `config` and `Tests` in this directory. Imo, they should be moved to the root of the application.
* I want to propose to lowercase `resources` for all bundles.

**Comment by iltar** [comment]
While we are at this subject, I'd like to expand on what @WouterJ mentioned with the Tests. I don't think that should be in bundles at all. It "pollutes" the structure and namespace. I'd like to make a proposition to put tests in `test/`, next to `src/` by default. This gives several benefits;
 - You can just put the same namespace autoloading on there with PSR-4
 - You can easily exclude it from deployments/packaging
 - You have your tests and code separated, code can't autoload tests/fixtures by accident but the other way around is possible with `autoload-dev`
 - No need to have tests in the `app/` directory.

Personally I have played around with the `App\` namespace in src. It's getting very close to ideal for me and gives a good Developers Experience, the only downside is that it's in `src/`. It makes it really easy to write down your namespaces and gives a clear distinguishable path between your app and other stuff.

```
app/Controller/Management/Account/CredentialsController.php
App\Controller\Management\Account\CredentialsController

// versus (my case, build before the AppBundle idea was introduced)
src/Bundle/AccountManagementBundle/Controller/CredentialsController.php
MyVendor\Bundle\AccountManagementBundle\Controlller\CredentialsController
```

It already became a lot better with the `AppBundle` - which you can just call `App` -, but now we got `src/App/AppBundle.php` and `app/AppKernel.php` which leads to confusion. I'm not sure how to deal with it for multiple kernels, but I have had no need for that before (Doesn't make sense dependency wise most of the cases).

**Comment by jvasseur** [comment]
@WouterJ The problem with keeping the AppBundle is that we would need to keep the @AppBundle notation and AppBundle doctrine alias for consistency.

I personally prefer removing the idea of an AppBundle and getting an App shortcut.

**Comment by WouterJ** [comment]
@jvasseur you can customize the name of the bundle in the bundle class. As you can see in the lib I referenced, it's very easy to have the `@App` notation and `App:...` aliases.

**Comment by jvasseur** [comment]
I know you can change the name, i just think that having a bundle that doesn't follow the conventions used for other bundles could be confusing.

**Comment by iltar** [comment]
You shouldn't see `app/*` as a bundle.

**Comment by weaverryan** [comment]
Hi guys!

Let me summarize some goals, the current structure and then the ongoing conversations

### Objectives

**From @fabpot in https://github.com/symfony/symfony-standard/issues/584#issuecomment-23126919**

* not too many directories/files under the root directory
* easy to understand directory/file names (using well-known names like `src/`, `var/`, or `bin/`)
* easy to find files based on their type (a PHP file should be in `src/` for instance)
* avoid a too deep directory structure for everything that needs to be edited by the developers on a regular basis (and an even less deep directory structure for ops guys)
* keep the directory structure easily manageable by Symfony (fixed names for the Kernel, ...)
* keep the current features easily implementable ("global" resources in the `Resources/` directory for instance)
* stick with the conventions we already have in Symfony (like the bundle dir structure)
* avoid names with a common prefix in the same directory (`console` vs `composer.json` for instance at the root)
* keep the possibility to have more than one application in a project

**My Additional Goals**

* Keep all the code to build a normal page (route, controller, template, etc) inside a single root directory
* Make this directory look and act consistent with a bundle

### Current Proposed

This includes moving `config/` to root, which is certainly still under discussion.

```
├── app
│  ├── AppCache.php
│  ├── AppKernel.php
│  ├── autoload.php
│  ├── Controller/
│  ├── Entity/
│  ├── Form/
│  ├── Resources/
│  ├── Tests
├── bin
│  ├── console
│  ├── symfony_requirements
├── config
│  ├── config.yml
│  ├── parameters.yml
│  ├── ...
├── src
│  ├── (empty, unless you choose to put PHP code here)
├── composer.json
├── composer.lock
├── phpunit.xml.dist
├── var
│   ├── cache
│   ├── logs
├── vendor
└── web
```

### A) Proposal: `app/config/` directory to root?

(This is shown in the directory structure above)

This breaks from the `app/` contract (that everything you need in your app is in this directory).

But `config/` is already one directory that is different than bundles anyways, and putting it at the root solves the capitalization problem in `app/`.

There was also decent support for this in #584 

### B) Proposal: `app/Tests` to root (by @iltar and @WouterJ)

Details: https://github.com/symfony/symfony-standard/issues/803#issuecomment-99000691

I can see two problems we should consider. First, the `app/` directory (in the above) *purposefully* looks exactly like a bundle structure (except for `config/`). Moving `Tests` out of `app/` violates this. Second, one of Fabien's requirements is to not get too many files/directories at the root.

### C) Proposal: Map `app` actually a bundle (by @WouterJ)

Details: https://github.com/symfony/symfony-standard/issues/803#issuecomment-98995243

Even if `app/` is not a bundle, it's a *kernel*, which (in the above proposal) has the same directory structure as a bundle and acts very similar too. That's not on accident: I want the kernel and bundle to have as much in common as possible. For that reason, I don't think we need to make this directory a bundle.

The downside to not making this a bundle is more BC breaks in documentation. The up-side is that things become more explicit (e.g. the entity `App` mapping: https://github.com/weaverryan/symfony-demo/blob/move_app_bundle/app/config/config.yml#L75). 

### D) Proposal: Lowercase `resources` in `app/` and bundles (by @WouterJ)

Details: https://github.com/symfony/symfony-standard/issues/803#issuecomment-98995243

I don't care too much about this either way, except that it would be a big BC break, and I don't see a big enough benefit.

**Comment by iltar** [comment]
@weaverryan I agree with Fabien's opinion, but as someone who had to work with tests.. They are scattered everywhere, hence my proposal. If you write tests for your Application, you also want to test your bundles and components/libraries. Having 1 root folder or dozens of folders scattered around is a big difference and easy to lose overview. If `src/` is meant for code, that means you'd want to exclude the ability to put tests in there as you _never_ want those to run in production. You can't exclude them from autoloading nor can you exclude the fixtures easily. It's also very hard to miss that they are in a nested `Test` directory. 

Maybe this problem deserves its own issue, but I'd like to see this address before 3.0 as right now people are putting the wrong stuff at the wrong locations. I think the `Test` directory standard was also created before PSR-4 was introduced and _IMO_ should be revised.

**Comment by WouterJ** [comment]
> Even if app/ is not a bundle, it's a kernel, which (in the above proposal) has the same directory structure as a bundle and acts very similar too. That's not on accident: I want the kernel and bundle to have as much in common as possible. For that reason, I don't think we need to make this directory a bundle.

> The downside to not making this a bundle is more BC breaks in documentation. The up-side is that things become more explicit

To be clear, I don't mean to add an `AppBundle.php` file inside `app/`. The big problem I see with this PR is a very big BC break for third party bundles relying on bundles (fixtures bundle is just one of many). If we could have a "virtual bundle" for the `app/` directory that is registered automatically, we have exactly the same behaviour but without BC break for any of these bundles.

> not too many directories/files under the root directory

I would like to add I don't like many files under a sub directory too. The reason I proposed to remove some files from the `app/` directory (tests & config) was based on this (personal) objective. It really feels like a wall of directories when navigating to `app/` in your repository. Knowing that I have to scroll through this wall each time I want to find the `config` directory (it's lowercased + not that long, so pretty hard to find) makes me wonder if it doesn't hurt DX more than it fixes.

**Comment by kumar2112** [comment]
Hello Guys . new for Mautic . i am overriding the Existing Mautic userBundle .
i want to know how to use complierspass . and how set the path of view using compiler pass .please help me.thanx in adance

**Comment by Pierstoval** [comment]
@kumar2112 http://symfony.com/doc/current/service_container/compiler_passes.html

**Comment by kumar2112** [comment]
Hello Pierstoval
     I want to know how to read the parent config files in  compilespass .do you have any demo.

**Comment by kumar2112** [comment]
@Pierstoval 
I want to know how to read the parent config in compilerspass

**Comment by xabbuh** [comment]
@kumar2112 Please use the [support channels](http://symfony.com/support) to seek for help.
